esphome:
  name: train-base
  includes: std_includes.h

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:

ota:
  platform: esphome

#ethernet:
#  type: LAN8720
#  mdc_pin: GPIO23
#  mdio_pin: GPIO18
#  clk_mode: GPIO17_OUT
#  phy_addr: 0
wifi:
  ssid: !secret SSID
  password: !secret password
  manual_ip:
    static_ip: 10.4.200.235
    gateway: 10.4.200.254
    subnet: 255.255.255.0

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

pca9685:
  - id: pca9685_hub1
    frequency: 500

mqtt:
  broker: 10.4.200.220
  discovery: false
  username: !secret mqtt
  password: !secret mqttpwd
  topic_prefix: train
  id: mqtt_ha
  on_json_message:
    - topic: train/rocrail/command
      then:
        - lambda: |-
            float bright;
            std::string server(x["server"]);
            std::string type(x["type"]);
            if (type == "co" && server != "mqttreader") {
              std::string lumiere(x["id"]);
              std::string cmd(x["cmd"]);
              bright=x["value"];
              auto lights=App.get_lights();
              int index=lights.size();
              for(unsigned int i = 0; i < lights.size(); i++) {
                if (lights[i]->get_name() == lumiere) index=i;
              }
              if (index == lights.size())
                ESP_LOGD("erreur", "index: %i", index);
              else {
                if (cmd == "on")
                  lights[index]->turn_on().perform();
                else
                  lights[index]->turn_off().perform();
              }
            }
            if (type == "sys" && server != "mqttreader") {
              std::string cmd(x["cmd"]);
              if (cmd == "go")
                id(AlimRail).publish_state(true);
              else
                id(AlimRail).publish_state(false);
            }
            if (type == "auto" && server != "mqttreader") {
              std::string cmd(x["cmd"]);
              if (cmd == "on")
                id(ModeAuto).publish_state(true);
              else
                id(ModeAuto).publish_state(false);
            }
            if (type == "lc" && server != "mqttreader") {
              std::string loco(x["id"]);
              if (x.containsKey("V")){
                int vitesse(x["V"]);
                std::string loco1=loco+"V";
                auto nombres=App.get_numbers();
                int index=nombres.size();
                for(unsigned int i = 0; i < nombres.size(); i++) {
                  if (nombres[i]->get_name() == loco1) index=i;
                }
                if (index == nombres.size())
                  ESP_LOGD("erreur", "index: %i", index);
                else
                  nombres[index]->publish_state(vitesse);
              }
              if (x.containsKey("dir")){
                std::string dir(x["dir"]);
                std::string loco1=loco+"A";
                auto  selects=App.get_selects();
                int index=selects.size();
                for(unsigned int i = 0; i < selects.size(); i++) {
                  if (selects[i]->get_name() == loco1) index=i;
                }
                if (index == selects.size())
                  ESP_LOGD("erreur", "index: %i", index);
                else 
                  if (dir == "true")
                    selects[index]->publish_state("avant");
                  else
                    selects[index]->publish_state("arriere");
              }
            }
            if (type == "fn" && server != "mqttreader") {
              std::string loco(x["id"]);
              std::string funcno(x["fnchanged"]);
              int no_f = std::stoi(funcno);
              std::string funcval0(x["f0"]);
              std::string funcval1(x["f1"]);
              std::string funcval6(x["f6"]);
              std::string funcval;
              switch (no_f){
                case 0:
                  funcval=funcval0;
                  break;
                case 1:
                  funcval=funcval1;
                  break;
                case 6:
                  funcval=funcval6;
                  break;
              }
              std::string loco1=loco+"f"+std::to_string(no_f);
              auto switchs=App.get_switches();
              int index=switchs.size();
              for(unsigned int i = 0; i < switchs.size(); i++) {
                if (switchs[i]->get_name() == loco1) index=i;
              }
              if (index == switchs.size())
                ESP_LOGD("erreur", "index: %i, %s", index, loco1.c_str());
              else
                if (funcval=="true")
                  switchs[index]->turn_on();
                else
                  switchs[index]->turn_off();
            }

output:
  - platform: pca9685
    channel: 0
    id: pwm00
  - platform: pca9685
    channel: 1
    id: pwm01
  - platform: pca9685
    channel: 2
    id: pwm02
  - platform: pca9685
    channel: 3
    id: pwm03
  - platform: pca9685
    channel: 4
    id: pwm04
  - platform: pca9685
    channel: 5
    id: pwm05
  - platform: pca9685
    channel: 6
    id: pwm06
  - platform: pca9685
    channel: 7
    id: pwm07
  - platform: pca9685
    channel: 8
    id: pwm08
  - platform: pca9685
    channel: 9
    id: pwm09
  - platform: pca9685
    channel: 10
    id: pwm10
  - platform: pca9685
    channel: 11
    id: pwm11
  - platform: pca9685
    channel: 12
    id: pwm12
  - platform: pca9685
    channel: 13
    id: pwm13
  - platform: pca9685
    channel: 14
    id: pwm14
  - platform: pca9685
    channel: 15
    id: pwm15

number:
  - platform: template
    id: BR206V
    name: "BR206V"
    icon: mdi:speedometer
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    on_value:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: !lambda |-
              int vitesse=lround(id(BR206V).state);
              return std::string("<lc id=\"BR206\" V=\"")+std::to_string(vitesse)+std::string("\"/>");
  - platform: template
    id: BR23V
    name: "BR23V"
    icon: mdi:speedometer
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    on_value:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: !lambda |-
              int vitesse=lround(id(BR23V).state);
              return std::string("<lc id=\"BR23\" V=\"")+std::to_string(vitesse)+std::string("\"/>");
  - platform: template
    id: BR74V
    name: "BR74V"
    icon: mdi:speedometer
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    on_value:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: !lambda |-
              int vitesse=lround(id(BR74V).state);
              return std::string("<lc id=\"BR74\" V=\"")+std::to_string(vitesse)+std::string("\"/>");
  - platform: template
    id: DB798V
    name: "DB798V"
    icon: mdi:speedometer
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    on_value:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: !lambda |-
              int vitesse=lround(id(DB798V).state);
              return std::string("<lc id=\"DB798\" V=\"")+std::to_string(vitesse)+std::string("\"/>");

select:
  - platform: template
    id: BR206A
    name: "BR206A"
    optimistic: true
    options:
      - avant
      - arriere
    initial_option: avant
    icon: mdi:forward
    on_value:
      then:
        - if:
            condition:
              - lambda: 'return id(BR206A).state == "avant";'
            then:
              - mqtt.publish:
                  topic: rocrail/service/client
                  payload: '<lc id="BR206" dir="true"/>'
            else:
              - mqtt.publish:
                  topic: rocrail/service/client
                  payload: '<lc id="BR206" dir="false"/>'

  - platform: template
    id: BR23A
    name: "BR23A"
    optimistic: true
    options:
      - avant
      - arriere
    initial_option: avant
    icon: mdi:forward
    on_value:
      then:
        - if:
            condition:
              - lambda: 'return id(BR23A).state == "avant";'
            then:
              - mqtt.publish:
                  topic: rocrail/service/client
                  payload: '<lc id="BR23" dir="true"/>'
            else:
              - mqtt.publish:
                  topic: rocrail/service/client
                  payload: '<lc id="BR23" dir="false"/>'

  - platform: template
    id: BR74A
    name: "BR74A"
    optimistic: true
    options:
      - avant
      - arriere
    initial_option: avant
    icon: mdi:forward
    on_value:
      then:
        - if:
            condition:
              - lambda: 'return id(BR74A).state == "avant";'
            then:
              - mqtt.publish:
                  topic: rocrail/service/client
                  payload: '<lc id="BR74" dir="true"/>'
            else:
              - mqtt.publish:
                  topic: rocrail/service/client
                  payload: '<lc id="BR74" dir="false"/>'

  - platform: template
    id: DB798A
    name: "DB798A"
    optimistic: true
    icon: mdi:forward
    options:
      - avant
      - arriere
    initial_option: avant
    on_value:
      then:
        - if:
            condition:
              - lambda: 'return id(DB798A).state == "avant";'
            then:
              - mqtt.publish:
                  topic: rocrail/service/client
                  payload: '<lc id="DB798" dir="true"/>'
            else:
              - mqtt.publish:
                  topic: rocrail/service/client
                  payload: '<lc id="DB798" dir="false"/>'

switch:
  - platform: template
    id: AlimRail
    name: "Alimentation rails"
    icon: mdi:fence-electric
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    on_turn_on:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<sys cmd="go"/>'
    on_turn_off:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<sys cmd="stop"/>'
  - platform: template
    id: ModeAuto
    name: "Automatique"
    icon: mdi:refresh-auto
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    on_turn_on:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<auto cmd="on"/>'
    on_turn_off:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<auto cmd="off"/>'
  - platform: template
    id: DB798f0
    name: "DB798f0"
    icon: mdi:car-light-high
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    on_turn_on:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<fn id="DB798" fnchangedstate="true" fnchanged="0" f0="true"/>'
    on_turn_off:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<fn id="DB798" fnchangedstate="true" fnchanged="0" f0="false"/>'
  - platform: template
    id: DB798f1
    name: "DB798f1"
    icon: mdi:dome-light
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    on_turn_on:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<fn id="DB798" fnchangedstate="true" fnchanged="1" f1="true"/>'
    on_turn_off:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<fn id="DB798" fnchangedstate="true" fnchanged="1" f1="false"/>'
  - platform: template
    id: DB798f6
    name: "DB798f6"
    icon: mdi:dome-light
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    on_turn_on:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<fn id="DB798" fnchangedstate="true" fnchanged="6" f6="true"/>'
    on_turn_off:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<fn id="DB798" fnchangedstate="true" fnchanged="6" f6="false"/>'
  - platform: template
    id: DB206f0
    name: "DB206f0"
    icon: mdi:car-light-high
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    on_turn_on:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<fn id="DB206" fnchangedstate="true" fnchanged="0" f0="true"/>'
    on_turn_off:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<fn id="DB206" fnchangedstate="true" fnchanged="0" f0="false"/>'
  - platform: template
    id: DB23f0
    name: "DB23f0"
    icon: mdi:car-light-high
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    on_turn_on:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<fn id="DB23" fnchangedstate="true" fnchanged="0" f0="true"/>'
    on_turn_off:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<fn id="DB23" fnchangedstate="true" fnchanged="0" f0="false"/>'
  - platform: template
    id: DB74f0
    name: "DB74f0"
    icon: mdi:car-light-high
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    on_turn_on:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<fn id="DB74" fnchangedstate="true" fnchanged="0" f0="true"/>'
    on_turn_off:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<fn id="DB74" fnchangedstate="true" fnchanged="0" f0="false"/>'



light:
  - platform: monochromatic
    name: 'GareB'
    id: GareB
    output: pwm00
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<co id="GareB" cmd="on"/>'
    on_turn_off:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<co id="GareB" cmd="off"/>'

  - platform: monochromatic
    name: 'GareH'
    id: GareH
    output: pwm01
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<co id="GareH" cmd="on"/>'
    on_turn_off:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<co id="GareH" cmd="off"/>'

  - platform: monochromatic
    name: 'Eglise'
    id: Eglise
    output: pwm02
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<co id="Eglise" cmd="on"/>'
    on_turn_off:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<co id="Eglise" cmd="off"/>'

  - platform: monochromatic
    name: 'QuaiB'
    id: QuaiB
    output: pwm03
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<co id="QuaiB" cmd="on"/>'
    on_turn_off:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<co id="QuaiB" cmd="off"/>'

  - platform: monochromatic
    name: 'Maison1'
    id: Maison1
    output: pwm04
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<co id="Maison1" cmd="on"/>'
    on_turn_off:
      then:
        - mqtt.publish:
            topic: rocrail/service/client
            payload: '<co id="Maison1" cmd="off"/>'

