esphome:
  name: train1-a16
  includes: std_includes.h

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: esp-idf

logger:

api:

ota:
  platform: esphome

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
#wifi:
#  ssid: !secret SSID
#  password: !secret password
  manual_ip:
    static_ip: 10.4.200.232
    gateway: 10.4.200.254
    subnet: 255.255.255.0

i2c:
  sda: 4
  scl: 5
  scan: true
  id: bus_a

pcf8574:
  - id: 'pcf8574_hub_out_1' # for output channel 1-8
    address: 0x24
    pcf8575: false
  - id: 'pcf8574_hub_out_2' # for output channel 9-16
    address: 0x25
    pcf8575: false
  - id: 'pcf8574_hub_in_1' # for input channel 1-8
    address: 0x22
    pcf8575: false
  - id: 'pcf8574_hub_in_2' # for input channel 9-16
    address: 0x21
    pcf8575: false

mqtt:
  broker: 10.4.200.220
  discovery: false
  username: !secret mqtt
  password: !secret mqttpwd
  on_json_message:
    topic: train/rocrail/command
    then:
      - lambda: |-
          std::string server(x["server"]);
          std::string type(x["type"]);
          if (type == "sw" && server != "mqttreader") {
            std::string aiguilage(x["id"]);
            std::string sens(x["cmd"]);
            auto selects=App.get_selects();
            int index=selects.size();
            for(unsigned int i = 0; i < selects.size(); i++) {
              if (selects[i]->get_name() == aiguilage) index=i;
            }
            if (index == selects.size())
              ESP_LOGD("erreur", "index: %i", index);
            else
              selects[index]->publish_state(sens); 
           }

packages:
  out0: !include
    file: outputs.yaml
    vars:
      nom: out00
      multiplex: pcf8574
      hub: pcf8574_hub_out_1
      num: 0
  out1: !include
    file: outputs.yaml
    vars:
      nom: out01
      multiplex: pcf8574
      hub: pcf8574_hub_out_1
      num: 1
  out2: !include
    file: outputs.yaml
    vars:
      nom: out02
      multiplex: pcf8574
      hub: pcf8574_hub_out_1
      num: 2
  out3: !include
    file: outputs.yaml
    vars:
      nom: out03
      multiplex: pcf8574
      hub: pcf8574_hub_out_1
      num: 3
  out4: !include
    file: outputs.yaml
    vars:
      nom: out04
      multiplex: pcf8574
      hub: pcf8574_hub_out_1
      num: 4
  out5: !include
    file: outputs.yaml
    vars:
      nom: out05
      multiplex: pcf8574
      hub: pcf8574_hub_out_1
      num: 5
  out6: !include
    file: outputs.yaml
    vars:
      nom: out06
      multiplex: pcf8574
      hub: pcf8574_hub_out_1
      num: 6
  out7: !include
    file: outputs.yaml
    vars:
      nom: out07
      multiplex: pcf8574
      hub: pcf8574_hub_out_1
      num: 7
  out8: !include
    file: outputs.yaml
    vars:
      nom: out08
      multiplex: pcf8574
      hub: pcf8574_hub_out_2
      num: 0
  out9: !include
    file: outputs.yaml
    vars:
      nom: out09
      multiplex: pcf8574
      hub: pcf8574_hub_out_2
      num: 1
  out10: !include
    file: outputs.yaml
    vars:
      nom: out10
      multiplex: pcf8574
      hub: pcf8574_hub_out_2
      num: 2
  out11: !include
    file: outputs.yaml
    vars:
      nom: out11
      multiplex: pcf8574
      hub: pcf8574_hub_out_2
      num: 3
  out12: !include
    file: outputs.yaml
    vars:
      nom: out12
      multiplex: pcf8574
      hub: pcf8574_hub_out_2
      num: 4
  out13: !include
    file: outputs.yaml
    vars:
      nom: out13
      multiplex: pcf8574
      hub: pcf8574_hub_out_2
      num: 5
  out14: !include
    file: outputs.yaml
    vars:
      nom: out14
      multiplex: pcf8574
      hub: pcf8574_hub_out_2
      num: 6
  out15: !include
    file: outputs.yaml
    vars:
      nom: out15
      multiplex: pcf8574
      hub: pcf8574_hub_out_2
      num: 7
  detect1: !include
    file: detecteurs.yaml
    vars:
      nom: gh7_in
      multiplex: pcf8574
      hub: pcf8574_hub_in_1
      pin: 0
  detect2: !include
    file: detecteurs.yaml
    vars:
      nom: gh1_in
      multiplex: pcf8574
      hub: pcf8574_hub_in_1
      pin: 1
  detect3: !include
    file: detecteurs.yaml
    vars:
      nom: gh1_enter
      multiplex: pcf8574
      hub: pcf8574_hub_in_1
      pin: 2
  detect4: !include
    file: detecteurs.yaml
    vars:
      nom: gh2_in
      multiplex: pcf8574
      hub: pcf8574_hub_in_1
      pin: 3
  detect5: !include
    file: detecteurs.yaml
    vars:
      nom: gh2_enter
      multiplex: pcf8574
      hub: pcf8574_hub_in_1
      pin: 4
  detect6: !include
    file: detecteurs.yaml
    vars:
      nom: gh3_in
      multiplex: pcf8574
      hub: pcf8574_hub_in_1
      pin: 5
  detect7: !include
    file: detecteurs.yaml
    vars:
      nom: gh4_in
      multiplex: pcf8574
      hub: pcf8574_hub_in_1
      pin: 6
  detect8: !include
    file: detecteurs.yaml
    vars:
      nom: gh5_in
      multiplex: pcf8574
      hub: pcf8574_hub_in_1
      pin: 7
  aiguil1: !include
    file: aiguillages.yaml
    vars:
      nom: Coul1Out
      sortieS: out00
      sortieT: out01
  aiguil2: !include
    file: aiguillages.yaml
    vars:
      nom: GB3In
      sortieS: out02
      sortieT: out03
  aiguil3: !include
    file: aiguillages.yaml
    vars:
      nom: GB2Out
      sortieS: out04
      sortieT: out05
  aiguil4: !include
    file: aiguillages.yaml
    vars:
      nom: GB2In
      sortieS: out06
      sortieT: out07
  aiguil5: !include
    file: aiguillages.yaml
    vars:
      nom: GB2GH
      sortieS: out07
      sortieT: out08
  aiguil6: !include
    file: aiguillages.yaml
    vars:
      nom: GB3Out
      sortieS: out10
      sortieT: out11
  aiguil7: !include
    file: aiguillages.yaml
    vars:
      nom: Coul1In
      sortieS: out12
      sortieT: out13
  aiguil8: !include
    file: aiguillages.yaml
    vars:
      nom: GH2Out
      sortieS: out14
      sortieT: out15

